anchor_version = "0.24.2"

[provider]
cluster = "localnet"
wallet = "oracle.key"

[programs.localnet]
draffle = "raFv43GLKy2ySi5oVExZxFGwdbKRRaDQBqikiY9YbVF"

[programs.devnet]
draffle = "raFv43GLKy2ySi5oVExZxFGwdbKRRaDQBqikiY9YbVF"

[programs.mainnet]
draffle = "raFv43GLKy2ySi5oVExZxFGwdbKRRaDQBqikiY9YbVF"

[scripts]
test = "mocha -t 1000000 programs/tests"

[registry]
url = "https://anchor.projectserum.com"
